
["Item Clear"]
	#Waiting time between Checks in Minutes
	#Range: 0 ~ 1440
	timer = 30
	#Text to display in TitleCommand
	titletext = "ITEMCLEAR INCOMING!"
	#Chat warning, Comma separated, in seconds
	warnings = "5,20"
	#Do a clear if there are more than X items
	#Range: > 0
	maximum = 1000
	#Text to Display in Chat when Item. First % will be replaced by Value. In red, encased in [=== 
	warningtext = "ITEMCLEAR IN % SECONDS"
	#Run a Title command on first warning
	title = true
	#Enable regular ItemClear
	enabled = false

["Memory Checker"]
	#Time between Memory Checks that will get saved for display(in seconds)
	#Range: > 0
	timer = 30
	#Threshold at which the Memory checker will diplay a warning in the Log (in MB)
	#Range: > 0
	threshold = 1000
	#Enable the Memory checker
	enabled = false
	#Run /spark heapdump when memory fills up more than 95 % the first time. This value gets set to false if this occurs
	heapdump = false

